### ISSUE TITLE
text on pictures is cropped  

### ISSUE THREAD

**Issue by ManoirEquivocal** [stevejwikeley/Equivocal#10]
you don't get to see all the text when the sentence is quite long on the picture, some words happen to be cut. Could the words go smaller when a window is reduced?
![text on pix cropped](https://cloud.githubusercontent.com/assets/9271222/7202920/09d15f92-e517-11e4-85f2-b43f7324db6b.jpg)

**Comment by stevejwikeley** [comment]
Amended on my local version will be fixed on the next update on the server
