### ISSUE TITLE
RIGHT text on pictures FRENCH

### ISSUE THREAD

**Issue by ManoirEquivocal** [stevejwikeley/Equivocal#7]
Image-caption-1=Une escapade hors champ
Image-caption-2=Cache-cache dans le labyrinthe de fleurs
Image-caption-3=La garantie d'une célébration réussie au Manoir Equivocal
Image-caption-4=Des équipements pour répondre à vos besoins 
Image-caption-5=Promenade dans les près
Image-caption-6=Un terrain de jeux inépuisable
Image-caption-7=La brume equivocal
Image-caption-8=no picture?
Image-caption-9=no picture?

**Comment by stevejwikeley** [comment]
cool - good job! You get the issue system 

![image](http://i.giphy.com/d89VuJ4GflFfO.gif)

**Comment by stevejwikeley** [comment]
Updated for next launch
