### ISSUE TITLE
RIGHT text on pictures ENGLISH

### ISSUE THREAD

**Issue by ManoirEquivocal** [stevejwikeley/Equivocal#8]
title=Home
Image-caption-1=A beautiful place to escape
Image-caption-2=Hide-and-seek in a flower maze
Image-caption-3=We help you to make it a perfect day
Image-caption-4=We have the facilities to make it happen
Image-caption-5=Clear your mind in the grounds
Image-caption-6=Have fun
Image-caption-7=A poetic hide away

**Comment by stevejwikeley** [comment]
Done - will be updated on next launch
