### ISSUE TITLE
sliding pictures

### ISSUE THREAD

**Issue by ManoirEquivocal** [stevejwikeley/Equivocal#9]
I believe people will get annoyed by the pictures moving alone. HOWEVER we should keep it this way but is it possible to include: 
- A standby button
- all the images visible in tiny size on the side on the streamer so people can jump from a picture to another. (when they feel like getting back to a picture) 
  Would it be possible to include those two things? 

Studies say people are annoyed by sliding pictures but if it doesn't move they will scroll down and not press on the arrows to see the next picture.

**Comment by stevejwikeley** [comment]
Will come back to this
